### ISSUE TITLE
Allow space in header name

### ISSUE THREAD

**Issue by er1z** [jgrygierek/BatchEntityImportBundle#81]
https://github.com/jgrygierek/BatchEntityImportBundle/blob/master/src/Model/Matrix/Matrix.php#L18

Can we have this regex to allow column name with space?

**Comment by jgrygierek** [comment]
Hi @er1z , can you check new version 3.1.0?

**Comment by er1z** [comment]
I wish I could, but we are tied to 2.0 for couple of next months.

**Comment by jgrygierek** [comment]
You mean 2.0 or 2.5? I can try to update it to version 2.6.

**Comment by er1z** [comment]
2.5, it'd be awesome if ported up there.

**Comment by jgrygierek** [comment]
Hi @er1z, done, check it now.

**Comment by er1z** [comment]
Need to upgrade to Sf5.x first, so it's gonna take a few weeks.

**Comment by jgrygierek** [comment]
Hi @er1z, how is the progress?
