### ISSUE TITLE
update deps

### ISSUE THREAD

**Issue by gulbinas** [jgrygierek/BatchEntityImportBundle#91]
please allow to use 
`    "sonata-project/admin-bundle": "^4.31",`
`        "doctrine/orm": "^3.1",`

in projects

**Comment by jgrygierek** [comment]
@gulbinas you mean the newest version of SonataBatchEntityImportBundle?

**Comment by jgrygierek** [comment]
@gulbinas version of `SonataAdminBundle` has been updated https://github.com/jgrygierek/SonataBatchEntityImportBundle/releases/tag/v2.7.0

**Comment by jgrygierek** [comment]
@gulbinas  do you still need `"doctrine/orm": "^3.1",`? Because it is set to `^2.9` in this package.
