### ISSUE TITLE
Allow doctrine/lexer ^2

### ISSUE THREAD

**Issue by ozahorulia** [jgrygierek/BatchEntityImportBundle#92]
Since #90 is blocked, can we just update doctrine/lexer dependency to "doctrine/lexer": "^1.2.1|^2.0" as it's done in that PR? It will not require any changes aside from the update requirement, but it will allow to update doctrine/orm to ^2.15, which is an important release for many other dependencies.

**Comment by jgrygierek** [comment]
Hi, I will check it

**Comment by jgrygierek** [comment]
@ozahorulia Done, check new version

**Comment by ozahorulia** [comment]
@jgrygierek looks perfect, thank you!
