### ISSUE TITLE
[TypeError] Allow array as type on import

### ISSUE THREAD

**Issue by rrr63** [jgrygierek/BatchEntityImportBundle#98]
Hi,

I think it could be a good feature to allow array type.

```php
//JG\BatchEntityImportBundle\Model\Configuration\AbstractImportConfiguration
if (method_exists($entity, $setterName)) {
    $reflection = new \ReflectionMethod($entity, $setterName);
    $params = $reflection->getParameters();

    if (!empty($params)) {
        $paramType = $params[0]->getType();
        if ($paramType && $paramType->getName() === 'array') {
            $value = explode('//', $value);
        }
    }
    $entity->$setterName($value);
}
```

Here is an example with a fixed separator `//`, but maybe it could be nice to allow user to override it, to use their own separator

**Comment by jgrygierek** [comment]
It is the simplest case. And it should be easy to allow just 1-dimensional array.


But there is a more advanced case:
Do we want only just simple 1-dimensional arrays? Or multidimensional too?
Do we want allow only indexes? Or maybe keys too?
Maybe better will be store it as json in file?

But currently probably such advanced feature is not needed?

**Comment by rrr63** [comment]
I think the 1d array is enough. 
To test i tried to import some `Users`, and there is the `roles` property.
Allow simple string or numeric array is already very good and will fix 80% of array usages imo

**Comment by jgrygierek** [comment]
Ok, I will try to do it maybe this weekend if I will have some time

**Comment by rrr63** [comment]
Maybe i can try to do a PR on this

**Comment by jgrygierek** [comment]
If you want, please do it :)

**Comment by jgrygierek** [comment]
@rrr63 
How we should convert values?

1. If we have `CSV` file with empty column for `ArrayType` it should it be converted into `[]`. But what if in CSV file we want to add v
3. But how there is a problem with array with empty element: `[0 => '']` or `[0 => null]`. I can't convert it to the `''`...

Do you habe any ideas how to distinguish `[]` and `[0 => '']`??

**Comment by jgrygierek** [comment]
@rrr63 Can you test it how it works in your app? And then we can think what else we need.

**Comment by rrr63** [comment]
@jgrygierek i tested, it works with simple array, i think it is enough for my usecase rn.
Maybe after users will need multi dimensional arrays ?
But if you merge, this issue will be solved

**Comment by jgrygierek** [comment]
@rrr63 Merged, you can use it now in normal way

**Comment by rrr63** [comment]
@jgrygierek thanks for all
